language: node_js
node_js:
  - "10"
install:
  - yarn install
script:
  - yarn clean
  - yarn embedded
  - yarn dev
  - yarn test-to-gh-pages
  - yarn test
deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: 'build'
    github_token: $GITHUB_TOKEN
    on:
      branch: master
notifications:
  slack: $SLACK_TOKEN
