name: 🐞 Bug report
description: Report a bug or unexpected behavior.
labels: "Bug"
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this form!
      
  - type: textarea
    id: what-happened
    attributes:
      label: Issue Details
      description: Please provide a set of steps to reproduce the issue.
      placeholder:
      value: |
        Steps to reproduce:
        1.
        2.
        3.
    validations:
      required: true
    
  - type: textarea
    id: screens
    attributes:
      label: Screenshots
      description: |
        If applicable add screenshots explaining your problem.
        You can drag and drop images or paste them from clipboard.
        Use `<details> </details>` tag to hide screenshots under the spoiler.
      placeholder: If applicable add screenshots explaining your problem.
      value: |
          <details><summary>Screenshot 1</summary>

          <!-- paste your screenshot here -->

          </details>
    validations:
      required: false  