---
version: 2
plan:
  project-key: ADGEXT
  key: LEGASSRELEASESPECS
  name: legacy assistant - build release
variables:
  dockerNode: adguard/node-ssh:22.17--0

stages:
  - Build:
      manual: false
      final: false
      jobs:
        - Build

Build:
  key: BUILD
  other:
    clean-working-dir: true
  docker:
    image: ${bamboo.dockerNode}
    volumes:
      ${system.PNPM_DIR}: "${bamboo.cachePnpm}"
  tasks:
    - checkout:
        force-clean-build: true
    - checkout:
        repository: extensions-private
        path: private
        force-clean-build: true
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -x
            set -e
            ls -alt

            pnpm install ${bamboo.varsPnpm}

            pnpm lint

            pnpm locales:validate-required

            pnpm release
    - inject-variables:
        file: build/release/build.txt
        scope: RESULT
        namespace: userscriptMeta
    - any-task:
        plugin-key: com.atlassian.bamboo.plugins.vcs:task.vcs.commit
        configuration:
          # do not change commitMessage as it does not trigger increment after deploy
          commitMessage: 'deploy: update dist v${bamboo.userscriptMeta.version}'
          selectedRepository: defaultRepository
    - any-task:
        plugin-key: com.atlassian.bamboo.plugins.vcs:task.vcs.tagging
        configuration:
          selectedRepository: defaultRepository
          tagName: v${bamboo.userscriptMeta.version}
  final-tasks:
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -x
            set -e

            # Fix mixed logs
            exec 2>&1

            ls -la

            echo "Size before cleanup:" && du -h | tail -n 1
            rm -rf node_modules
            echo "Size after cleanup:" && du -h | tail -n 1
  artifacts:
    - name: assistant.meta.js
      location: build/release
      pattern: assistant.meta.js
      shared: true
      required: true
    - name: assistant.user.js
      location: build/release
      pattern: assistant.user.js
      shared: true
      required: true
  requirements:
    - adg-docker: 'true'

triggers: []

branches:
  create: manually
  delete: never
  link-to-jira: true

notifications:
  - events:
      - plan-status-changed
    recipients:
      - webhook:
          name: Build webhook
          url: http://prod.jirahub.service.eu.consul/v1/webhook/bamboo
labels: []
other:
  concurrent-build-plugin: system-default
