---
version: 2
plan:
  project-key: ADGEXT
  key: LEGASSBETASPECS
  name: legacy assistant - build beta
variables:
  dockerNode: adguard/node-ssh:16.17--1

stages:
  - Build:
      manual: 'false'
      final: 'false'
      jobs:
        - Build

Build:
  key: BUILD
  other:
    clean-working-dir: true
  docker:
    image: ${bamboo.dockerNode}
    volumes:
      ${system.YARN_DIR}: "${bamboo.cacheYarn}"
  tasks:
    - checkout:
        force-clean-build: 'true'
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -x
            set -e
            ls -alt

            yarn install ${bamboo.varsYarn}
            yarn beta
            rm -rf node_modules
    - inject-variables:
        file: build/beta/build.txt
        scope: RESULT
        namespace: userscriptMeta
    - any-task:
        plugin-key: com.atlassian.bamboo.plugins.vcs:task.vcs.tagging
        configuration:
          selectedRepository: defaultRepository
          tagName: v${bamboo.userscriptMeta.version}-beta
  artifacts:
    - name: assistant.meta.js
      location: build/beta
      pattern: assistant.meta.js
      shared: true
      required: true
    - name: assistant.user.js
      location: build/beta
      pattern: assistant.user.js
      shared: true
      required: true
  requirements:
    - adg-docker: 'true'

triggers: []

branches:
  create: manually
  delete: never
  link-to-jira: 'true'

notifications:
  - events:
      - plan-status-changed
    recipients:
      - webhook:
          name: Build webhook
          url: http://prod.jirahub.service.eu.consul/v1/webhook/bamboo
labels: []
other:
  concurrent-build-plugin: system-default
