---
version: 2
plan:
  project-key: ADGEXT
  key: LEGASSRELEASESPECS
  name: legacy assistant - build release
variables:
  dockerNode: node:15.14.0-buster-slim

stages:
  - Build:
      manual: 'false'
      final: 'false'
      jobs:
        - Build

Build:
  key: BUILD
  other:
    clean-working-dir: true
  docker:
    image: ${bamboo.dockerNode}
    volumes:
      ${system.YARN_DIR}: "${bamboo.cacheYarn}"
  tasks:
    - checkout:
        force-clean-build: 'true'
    - checkout:
        repository: extensions-private
        path: private
        force-clean-build: 'true'
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -x
            set -e
            ls -alt

            yarn install ${system.YARN_ARGS}
            yarn release

    - inject-variables:
        file: build/release/build.txt
        scope: RESULT
        namespace: userscriptMeta
    - any-task:
        plugin-key: com.atlassian.bamboo.plugins.vcs:task.vcs.tagging
        configuration:
          selectedRepository: defaultRepository
          tagName: v${bamboo.userscriptMeta.version}
  artifacts:
    - name: assistant.meta.js
      location: build/release
      pattern: assistant.meta.js
      shared: true
      required: true
    - name: assistant.user.js
      location: build/release
      pattern: assistant.user.js
      shared: true
      required: true
  requirements:
    - adg-docker: 'true'

triggers: []

branches:
  create: manually
  delete: never
  link-to-jira: 'true'

notifications:
  - events:
      - plan-status-changed
    recipients:
      - webhook:
          name: Build webhook
          url: http://prod.jirahub.service.eu.consul/v1/webhook/bamboo?channel=adguard-qa
labels: []
other:
  concurrent-build-plugin: system-default
