---
version: 2
plan:
  project-key: ADGEXT
  key: LEGASSTESTSPECS
  name: legacy assistant - test
variables:
  dockerPuppeteer: adguard/puppeteer-runner:22.14--24.5--0

stages:
  - Test:
      manual: false
      final: false
      jobs:
        - Test

Test:
  key: TEST
  other:
    clean-working-dir: true
  docker:
    image: ${bamboo.dockerPuppeteer}
    volumes:
      ${system.PNPM_DIR}: "${bamboo.cachePnpm}"
  tasks:
    - checkout:
        force-clean-build: true
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -x
            set -e

            # Fix mixed logs
            exec 2>&1

            ls -laht

            # Exclude '--ignore-scripts' from pnpm arguments
            # since it prevents postinstall scripts from running
            # so Chrome is not installed which is crucial for tests
            originalPnpmArgs="$bamboo_varsPnpm"
            modifiedPnpmArgs=$(echo "$originalPnpmArgs" | sed 's/--ignore-scripts//g')

            # Install dependencies
            pnpm install ${modifiedPnpmArgs}

            pnpm lint

            pnpm dev

            pnpm test
  final-tasks:
    - script:
        interpreter: SHELL
        scripts:
          - |-
            set -x
            set -e

            # Fix mixed logs
            exec 2>&1

            ls -la

            echo "Size before cleanup:" && du -h | tail -n 1
            rm -rf node_modules
            echo "Size after cleanup:" && du -h | tail -n 1
  artifacts:
    - name: assistant.meta.js
      location: build/dev
      pattern: assistant.meta.js
      shared: true
      required: true
    - name: assistant.js
      location: build/dev
      pattern: assistant.js
      shared: true
      required: true
    - name: assistant.user.js
      location: build/dev
      pattern: assistant.user.js
      shared: true
      required: true
  requirements:
    - extension: 'true'

branches:
  create: for-pull-request
  delete:
    after-deleted-days: '1'
    after-inactive-days: '5'
  link-to-jira: true

notifications: []
labels: []
other:
  concurrent-build-plugin: system-default
